insert into relationship (description) values ('Father');
insert into relationship (description) values ('Mother');
insert into relationship (description) values ('Grandmother');
insert into relationship (description) values ('Grandfather');
insert into relationship (description) values ('Sister');
insert into relationship (description) values ('Brother');
insert into relationship (description) values ('Childminder');
insert into relationship (description) values ('Aunt');
insert into relationship (description) values ('Uncle');
insert into relationship (description) values ('Friend');

insert into events (description) values ('Playdate as guest');
insert into events (description) values ('Playdate as host');
insert into events (description) values ('Park visit');
insert into events (description) values ('Birthday Party');
insert into events (description) values ('Restaurant');
insert into events (description) values ('Cafe');
insert into events (description) values ('Softplay');
insert into events (description) values ('Babysit');
insert into events (description) values ('Childmind');
insert into events (description) values ('Theatre');
insert into events (description) values ('Open farm');
insert into events (description) values ('aquarium');
insert into events (description) values ('Family visit');
insert into events (description) values ('Seasonal occasion');
insert into events (description) values ('Sport practice');
insert into events (description) values ('swimming');