insert into relationship_types (name) values ('Father');
insert into relationship_types (name) values ('Mother');
-- insert into relationship_types (name) values ('Grandmother');
-- insert into relationship_types (name) values ('Grandfather');
-- insert into relationship_types (name) values ('Sister');
-- insert into relationship_types (name) values ('Brother');
-- insert into relationship_types (name) values ('Childminder');
-- insert into relationship_types (name) values ('Aunt');
-- insert into relationship_types (name) values ('Uncle');
-- insert into relationship_types (name) values ('Friend');
-- insert into relationship_types (name) values ('Child');