version: '3.4'
services:
  db:
    image: postgres:14-bullseye
    container_name: childcare_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: childcare
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  flyway:
     image: flyway/flyway:9-alpine
     container_name: childcare_flyway
     command: -url=jdbc:postgresql://db/childcare -schemas=public -user=admin
       -password=password -connectRetries=5 migrate
     volumes:
       - ./migrations:/flyway/sql
     depends_on:
       - db
volumes:
  db:
    name: childcare_postgres
  # pgadmin: